## Auto-Scaling Variables
variable "application_name_prefix" {}
variable "image_id" {}
variable "instance_type" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "vpc_zone_identifier" {}
variable "instance_key" {}
variable "lb_security_group_id" {}
variable "vpc_id" {}